Name: Recipe
Type: FolderType
Children:
- Name: RecipeDataLine1
  Id: g=4c8e8fd3c28c623497d0dcaf621df10b
  Type: BaseObjectType
  Children:
  - Name: WaterWeight
    Type: BaseDataVariableType
    DataType: Float
  - Name: SyrupWeight
    Type: BaseDataVariableType
    DataType: Float
  - Name: SugarWeight
    Type: BaseDataVariableType
    DataType: Float
  - Name: MixingSpeed
    Type: BaseDataVariableType
    DataType: UInt16
  - Name: MixingTime
    Type: BaseDataVariableType
    DataType: UInt16
- Name: RecipeDataLine2
  Id: g=b9fc9677a4a877393425f67779f79807
  Type: BaseObjectType
  Children:
  - Name: WaterWeight
    Type: BaseDataVariableType
    DataType: Float
  - Name: SyrupWeight
    Type: BaseDataVariableType
    DataType: Float
  - Name: SugarWeight
    Type: BaseDataVariableType
    DataType: Float
  - Name: MixingSpeed
    Type: BaseDataVariableType
    DataType: UInt16
  - Name: MixingTime
    Type: BaseDataVariableType
    DataType: UInt16
- Name: RecipeDataLine3
  Id: g=e4dee421ec8b7f0518fcfcbca0968774
  Type: BaseObjectType
  Children:
  - Name: WaterWeight
    Type: BaseDataVariableType
    DataType: Float
  - Name: SyrupWeight
    Type: BaseDataVariableType
    DataType: Float
  - Name: SugarWeight
    Type: BaseDataVariableType
    DataType: Float
  - Name: MixingSpeed
    Type: BaseDataVariableType
    DataType: UInt16
  - Name: MixingTime
    Type: BaseDataVariableType
    DataType: UInt16
